// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtr8XlYncXo9tTgtpJBqpb1Il-EjRmlyc',
    appId: '1:446545621072:web:1a91fcd0792f04d9de6155',
    messagingSenderId: '446545621072',
    projectId: 'estoque-app-5db52',
    authDomain: 'estoque-app-5db52.firebaseapp.com',
    storageBucket: 'estoque-app-5db52.firebasestorage.app',
    measurementId: 'G-PN2ED4NGTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7r24i0-46Du3cApppwndnBrbjsv5fSc0',
    appId: '1:446545621072:android:2f7ccedd6d110c62de6155',
    messagingSenderId: '446545621072',
    projectId: 'estoque-app-5db52',
    storageBucket: 'estoque-app-5db52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHFFfcSbBQ_j1J9j5Wvjkxn6ubyn8278w',
    appId: '1:446545621072:ios:0632f74b39b7c665de6155',
    messagingSenderId: '446545621072',
    projectId: 'estoque-app-5db52',
    storageBucket: 'estoque-app-5db52.firebasestorage.app',
    iosBundleId: 'com.example.estoqueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHFFfcSbBQ_j1J9j5Wvjkxn6ubyn8278w',
    appId: '1:446545621072:ios:0632f74b39b7c665de6155',
    messagingSenderId: '446545621072',
    projectId: 'estoque-app-5db52',
    storageBucket: 'estoque-app-5db52.firebasestorage.app',
    iosBundleId: 'com.example.estoqueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtr8XlYncXo9tTgtpJBqpb1Il-EjRmlyc',
    appId: '1:446545621072:web:3a4bff3024eb0dbdde6155',
    messagingSenderId: '446545621072',
    projectId: 'estoque-app-5db52',
    authDomain: 'estoque-app-5db52.firebaseapp.com',
    storageBucket: 'estoque-app-5db52.firebasestorage.app',
    measurementId: 'G-R7FJPYPGE0',
  );
}
